// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'datav-edit-header': string;
  'drawer-actions': string;
  'editor-config': string;
  'editor-header-wp': string;
  'global-actions': string;
  'hcenter': string;
  'header': string;
  'header-button': string;
  'heartBeat': string;
  'marqueeAnimation': string;
  'ml4': string;
  'node-config': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'screen-info': string;
  'selected': string;
  'vcenter': string;
  'workspace-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
