// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ceil': string;
  'dv-scroll-board': string;
  'header': string;
  'header-item': string;
  'hoverAble': string;
  'index': string;
  'row-item': string;
  'rows': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
