// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignColumn': string;
  'alignRow': string;
  'ceil': string;
  'center': string;
  'dv-scroll-board': string;
  'hcenter': string;
  'header': string;
  'header-item': string;
  'heartBeat': string;
  'index': string;
  'marqueeAnimation': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'row-item': string;
  'rows': string;
  'text': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
