// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'dv-scroll-ranking-board': string;
  'hcenter': string;
  'heartBeat': string;
  'info-name': string;
  'info-value': string;
  'inside-column': string;
  'marqueeAnimation': string;
  'rank': string;
  'ranking-column': string;
  'ranking-info': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'row-item': string;
  'shine': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
