// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'business': string;
  'center': string;
  'clear-search-text': string;
  'closeBtn': string;
  'component-panel': string;
  'component-panel-wp': string;
  'component-panel-wrapper': string;
  'component-search-wp': string;
  'components-from-text': string;
  'components-info': string;
  'components-item-img': string;
  'content': string;
  'datav-tabs': string;
  'ellipsis': string;
  'finished': string;
  'flex-wp': string;
  'hcenter': string;
  'heartBeat': string;
  'hide': string;
  'img': string;
  'line': string;
  'line1': string;
  'line2': string;
  'marqueeAnimation': string;
  'mask': string;
  'menulist': string;
  'nav': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'search-ipt': string;
  'searchResult': string;
  'tab': string;
  'tabActived': string;
  'text': string;
  'vcenter': string;
  'wp': string;
}
export const cssExports: CssExports;
export default cssExports;
