// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'zoom': string;
  'zoomContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
