// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'body': string;
  'bottom': string;
  'btn': string;
  'center': string;
  'config-panel-wp': string;
  'configPanelTransparent': string;
  'datav-gui': string;
  'hcenter': string;
  'head': string;
  'heartBeat': string;
  'hide': string;
  'img': string;
  'json': string;
  'jsonwrapper': string;
  'marqueeAnimation': string;
  'pageconfig': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'title': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
