// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'bottom': string;
  'hide': string;
  'layerPanel': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
