// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'border': string;
  'demo': string;
  'name': string;
  'pie_charts': string;
  'tip': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
