// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'configGrid': string;
  'configList': string;
  'hcenter': string;
  'heartBeat': string;
  'img': string;
  'item': string;
  'itemActive': string;
  'marqueeAnimation': string;
  'name': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
