// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'chartItem': string;
  'progress-bar': string;
  'progress-bar-bar': string;
  'progress-bar-bar-light': string;
  'progress-bar-tip': string;
  'progress-bar-triangle': string;
  'progress-bar-warpper': string;
}
export const cssExports: CssExports;
export default cssExports;
