// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bounce': string;
  'box': string;
  'container': string;
  'detailContainer': string;
  'dot': string;
  'legend': string;
  'legendItem': string;
  'waffleContainer': string;
  'waffleTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
