// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'active': string;
  'bounce': string;
  'box': string;
  'container': string;
  'waffleContainer': string;
  'waffleTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
