// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bounce': string;
  'box': string;
  'container': string;
}
export const cssExports: CssExports;
export default cssExports;
