// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'button-span': string;
  'color-notpublish': string;
  'color-publish': string;
  'edit': string;
  'headerImg': string;
  'img': string;
  'info': string;
  'input': string;
  'list': string;
  'main': string;
  'main-button': string;
  'main-project': string;
  'manage-main': string;
  'manage-title': string;
  'my-project': string;
  'name-icon': string;
  'nav-img': string;
  'nav-img-text': string;
  'navMain': string;
  'navShadow': string;
  'new': string;
  'project': string;
  'project-all': string;
  'project-block': string;
  'project-checked-color': string;
  'project-group': string;
  'project-name': string;
  'project-num': string;
  'project-ungrouped': string;
  'projectList': string;
  'projectManage': string;
  'publish-info': string;
  'screen': string;
  'screen-name-input': string;
  'screenItem': string;
  'screenMain': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
