// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignColumn': string;
  'alignRow': string;
  'blueTheme': string;
  'center': string;
  'counter': string;
  'digitalScroll': string;
  'hcenter': string;
  'heartBeat': string;
  'item': string;
  'marqueeAnimation': string;
  'num': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'vcenter': string;
  'whiteTheme': string;
}
export const cssExports: CssExports;
export default cssExports;
