// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'curtain': string;
  'curtain-exit-active': string;
  'dna': string;
  'dot': string;
  'ele': string;
  'rotate': string;
  'tip': string;
}
export const cssExports: CssExports;
export default cssExports;
