// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'disabled': string;
  'input-range': string;
  'range': string;
  'rangeWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
