// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'chartWrapper': string;
  'editor': string;
  'editor-panel-wp': string;
  'hcenter': string;
  'heartBeat': string;
  'hide': string;
  'main': string;
  'marqueeAnimation': string;
  'right-edit-main': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
