// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'arrayTop': string;
  'colorItem': string;
  'colorPanel': string;
  'fields': string;
  'gardient': string;
  'head': string;
  'item': string;
  'itemWrapper': string;
  'rectPop': string;
  'tools': string;
}
export const cssExports: CssExports;
export default cssExports;
