// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'dragging': string;
  'enable': string;
  'group_item': string;
  'hcenter': string;
  'heartBeat': string;
  'hided': string;
  'img': string;
  'last-flex-item': string;
  'layer-manager-layout-selector': string;
  'layer-manager-top': string;
  'layer-num': string;
  'layer-panel-wp': string;
  'layer-thumbail-item': string;
  'layer-toolbar': string;
  'layer-toolbar-bottom': string;
  'layer-toolbar-icon': string;
  'layerWrap': string;
  'locked': string;
  'marqueeAnimation': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'selected': string;
  'text': string;
  'thumbnail': string;
  'toolbar': string;
  'ul': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
