// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chart-wrapper': string;
  'trend-wrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
