import { IChartMock } from '@/component/chartItem/interface';
export let mock: IChartMock = {
  data: [
    { year: '周一', value: 120, category: '邮件营销' },
    { year: '周一', value: 132, category: '联盟广告' },
    { year: '周一', value: 101, category: '视频广告' },
    { year: '周一', value: 134, category: '直接访问' },
    { year: '周一', value: 90, category: '搜索引擎' },
    { year: '周二', value: 220, category: '邮件营销' },
    { year: '周二', value: 182, category: '联盟广告' },
    { year: '周二', value: 191, category: '视频广告' },
    { year: '周二', value: 234, category: '直接访问' },
    { year: '周二', value: 290, category: '搜索引擎' },
    { year: '周三', value: 150, category: '邮件营销' },
    { year: '周三', value: 232, category: '联盟广告' },
    { year: '周三', value: 201, category: '视频广告' },
    { year: '周三', value: 154, category: '直接访问' },
    { year: '周三', value: 190, category: '搜索引擎' },
    { year: '周四', value: 320, category: '邮件营销' },
    { year: '周四', value: 332, category: '联盟广告' },
    { year: '周四', value: 301, category: '视频广告' },
    { year: '周四', value: 334, category: '直接访问' },
    { year: '周四', value: 390, category: '搜索引擎' },
    { year: '周五', value: 820, category: '邮件营销' },
    { year: '周五', value: 932, category: '联盟广告' },
    { year: '周五', value: 901, category: '视频广告' },
    { year: '周五', value: 934, category: '直接访问' },
    { year: '周五', value: 1290, category: '搜索引擎' },
  ],
  title: '某数据_MOCK数据',
  header: ['year', 'value', 'category'],
  rows: 10,
  hash: 'mockdata',
};
