// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'imglist': string;
  'popContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
