// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'datav-thumbnail': string;
  'hcenter': string;
  'heartBeat': string;
  'marqueeAnimation': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'select-span': string;
  'thumbnail': string;
  'thumbnail-hide': string;
  'thumbnail-show': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
