// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'hcenter': string;
  'heartBeat': string;
  'marqueeAnimation': string;
  'mock_guide': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
