// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'borderImg': string;
  'widgetBorder': string;
}
export const cssExports: CssExports;
export default cssExports;
