// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'hcenter': string;
  'heartBeat': string;
  'li': string;
  'marqueeAnimation': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
