// This file is automatically generated.
// Please do not change this file!
type CssExports = {
  'alignColumn': string;
  'alignRow': string;
  'center': string;
  'hcenter': string;
  'heartBeat': string;
  'history-manager-panel-wp': string;
  'layer-manager-layout-selector': string;
  'layer-manager-top': string;
  'layer-num': string;
  'marqueeAnimation': string;
  'rotateCustom': string;
  'rotateX': string;
  'rotateY': string;
  'rotateZ': string;
  'rotateZReverse': string;
  'ul': string;
  'vcenter': string;
}
export const cssExports: CssExports;
export default cssExports;
